spring:
  application:
    name: jcaboclo-spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JoaoCaboclo/jcaboclo-spring-cloud-environment-variable.git
server:
  port: ${port:8888}
